version: '3.1'

services:
  database:
    image: it-talent-desafio-junho-database
    ports:
      - "3306:3036"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mysql
